version: '3.2'
services:
  alertmanager:
    image: prom/alertmanager:latest
    ports:
    - 9093:9093
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
    - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./prometheus:/etc/prometheus:ro
  amtool:
    build:
      context: amtool
    volumes:
    - ./amtool/config.yml:/etc/amtool/config.yml:ro
  hello:
    build:
      context: hello
      args:
        goPackage: github.com/lucperkins/prometheus-playground/alertmanager/hello
      cache_from:
      - golang:1.10
      - scratch
    ports:
    - 2112:2112
  webhook:
    build:
      context: webhook
      args:
        goPackage: github.com/lucperkins/prometheus-playground/alertmanager/webhook
      cache_from:
      - golang:1.10
      - scratch
    ports:
    - 5001:5001
