version: '3.2'
services:
  haproxy:
    image: haproxy:alpine
    ports:
    - 443:443
    volumes:
    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    - ./certs:/etc/ssl/certs:ro
    depends_on:
    - prometheus
  prometheus:
    image: prom/prometheus:latest
    expose:
    - 9090
    command:
    - --web.route-prefix=/prometheus
    - --web.external-url=http://example.com
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
