version: '3.2'
services:
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx:/etc/nginx:ro
    - ./certs:/root/certs/example.com
    ports:
    - 443:443
    links:
    - prometheus:prometheus
    depends_on:
    - prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.route-prefix=/
    - --web.external-url=http://example.com/prometheus
    volumes:
    - ./prometheus:/etc/prometheus
